server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis/SqlMapperConfig.xml

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/umanager?useSSL=false&autoReconnect=true
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    dbcp2:
#      validation-query: 'select 1'
#      test-on-borrow: true
#      test-while-idle: true
#      time-between-eviction-runs-millis: 27800
#      initial-size: 5
#      min-idle: 5
#      max-idle: 100
#      max-wait-millis: 10000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umanager?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #连接池配置
    initial-size: 10
    max-active: 20
    min-idle: 5
    max-wait: 30000
    time-between-eviction-runs-millis: 40000


  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
